// convex/data.ts
// This file is a "clean" version of the product data specifically for seeding Convex.
// It avoids importing image files directly to prevent build errors in the Convex environment.

export const SEED_PRODUCTS = [
    {
        name: "DAUST Water Bottle",
        category: "Drinkware",
        price: 15.0,
        rating: 4.8,
        badge: "Popular",
        image: "/assets/GoodiesMedias/Goodies/bottle.png",
        images: ["/assets/GoodiesMedias/Goodies/bottle.png", "/assets/GoodiesMedias/Goodies/mug.png"],
        colors: [{ name: "Steel", hex: "#94a3b8" }, { name: "Navy", hex: "#0a2342" }],
        description: "Stay hydrated on campus with our premium DAUST Water Bottle. Designed for durability and style.",
    },
    {
        name: "DAUST Mug",
        category: "Drinkware",
        price: 10.0,
        rating: 4.7,
        image: "/assets/GoodiesMedias/Goodies/mug.png",
        images: ["/assets/GoodiesMedias/Goodies/mug.png", "/assets/GoodiesMedias/Goodies/bottle.png"],
        colors: [{ name: "White", hex: "#ffffff" }],
        description: "The perfect companion for your morning coffee or late-night study sessions.",
    },
    {
        name: "DAUST Cap (Blue)",
        category: "Caps",
        price: 12.0,
        rating: 4.6,
        image: "/assets/GoodiesMedias/Goodies/cap-blue.png",
        images: ["/assets/GoodiesMedias/Goodies/cap-blue.png"],
        colors: [{ name: "Blue", hex: "#1e40af" }],
        sizes: ["Adjustable"],
        description: "Classic 6-panel cap with our iconic DAUST logo embroidered on the front.",
    },
    {
        name: 'Hoodie "Once/Always a DAUST innovator" (White)',
        category: "Hoodies",
        price: 35.0,
        rating: 4.9,
        image: "/assets/GoodiesMedias/Goodies/hoodie-oncealways-white.png",
        images: ["/assets/GoodiesMedias/Goodies/hoodie-oncealways-white.png", "/assets/GoodiesMedias/Goodies/hoodies-oncealways.png"],
        colors: [{ name: "White", hex: "#ffffff" }],
        sizes: ["S", "M", "L", "XL"],
        description: "Premium cotton-blend hoodie that represents the spirit of DAUST.",
    },
    {
        name: 'Hoodie "Proud Parent" (Grey)',
        category: "Hoodies",
        price: 35.0,
        rating: 4.7,
        image: "/assets/GoodiesMedias/Goodies/hoodie-proud-grey.png",
        images: ["/assets/GoodiesMedias/Goodies/hoodie-proud-grey.png", "/assets/GoodiesMedias/Goodies/hoodie-proud-white.png"],
        colors: [{ name: "Grey", hex: "#9ca3af" }],
        sizes: ["M", "L", "XL", "2XL"],
        description: "Show your family pride with the Official DAUST Proud Parent hoodie.",
    },
    {
        name: 'Hoodie "Proud Parent" (White)',
        category: "Hoodies",
        price: 35.0,
        rating: 4.7,
        image: "/assets/GoodiesMedias/Goodies/hoodie-proud-white.png",
        images: ["/assets/GoodiesMedias/Goodies/hoodie-proud-white.png", "/assets/GoodiesMedias/Goodies/hoodie-proud-grey.png"],
        colors: [{ name: "White", hex: "#ffffff" }],
        sizes: ["M", "L", "XL", "2XL"],
        description: "Show your family pride with the Official DAUST Proud Parent hoodie in White.",
    },
    {
        name: 'Hoodies "Once/Always a DAUST innovator" ',
        category: "Hoodies",
        price: 35.0,
        rating: 4.6,
        image: "/assets/GoodiesMedias/Goodies/hoodies-oncealways.png",
        images: ["/assets/GoodiesMedias/Goodies/hoodies-oncealways.png", "/assets/GoodiesMedias/Goodies/hoodie-oncealways-white.png"],
        colors: [{ name: "Navy", hex: "#0a2342" }],
        sizes: ["S", "M", "L", "XL"],
        description: "The complete collection of 'Once/Always' hoodies for the DAUST community.",
    },
    {
        name: "T-Shirt Code Build Impact (Blue)",
        category: "T-Shirts",
        price: 18.0,
        rating: 4.5,
        image: "/assets/GoodiesMedias/Goodies/tshirt-cbi-blue.png",
        images: ["/assets/GoodiesMedias/Goodies/tshirt-cbi-blue.png", "/assets/GoodiesMedias/Goodies/tshirts-cbi.png"],
        colors: [{ name: "Blue", hex: "#0a2342" }],
        sizes: ["S", "M", "L", "XL"],
        description: "Code. Build. Impact. The engineer's uniform for making a difference.",
    },
    {
        name: "T-Shirt ELEC Engineer (Grey)",
        category: "T-Shirts",
        price: 18.0,
        rating: 4.5,
        image: "/assets/GoodiesMedias/Goodies/tshirt-elec-grey.png",
        images: ["/assets/GoodiesMedias/Goodies/tshirt-elec-grey.png", "/assets/GoodiesMedias/Goodies/tshirts-elec.png"],
        colors: [{ name: "Grey", hex: "#9ca3af" }],
        sizes: ["S", "M", "L", "XL"],
        description: "Official ELEC Engineering T-Shirt. Represent your department with pride.",
    },
    {
        name: "T-Shirts Code Build Impact ",
        category: "T-Shirts",
        price: 18.0,
        rating: 4.4,
        image: "/assets/GoodiesMedias/Goodies/tshirts-cbi.png",
        images: ["/assets/GoodiesMedias/Goodies/tshirts-cbi.png", "/assets/GoodiesMedias/Goodies/tshirt-cbi-blue.png"],
        colors: [{ name: "Navy", hex: "#0a2342" }],
        sizes: ["S", "M", "L", "XL"],
        description: "Multiple styles of the Code Build Impact T-Shirt collection.",
    },
    {
        name: "T-Shirts ELEC Engineer ",
        category: "T-Shirts",
        price: 18.0,
        rating: 4.4,
        image: "/assets/GoodiesMedias/Goodies/tshirts-elec.png",
        images: ["/assets/GoodiesMedias/Goodies/tshirts-elec.png", "/assets/GoodiesMedias/Goodies/tshirt-elec-grey.png"],
        colors: [{ name: "Grey", hex: "#9ca3af" }],
        sizes: ["S", "M", "L", "XL"],
        description: "The complete ELEC Engineer T-Shirt collection.",
    },
    {
        name: "T-Shirts DAUST Innovator ",
        category: "T-Shirts",
        price: 18.0,
        rating: 4.4,
        image: "/assets/GoodiesMedias/Goodies/tshirts-innov.png",
        images: ["/assets/GoodiesMedias/Goodies/tshirts-innov.png"],
        colors: [{ name: "White", hex: "#ffffff" }],
        sizes: ["S", "M", "L", "XL"],
        description: "Celebration of innovation at DAUST. A light and comfortable T-Shirt.",
    },
    {
        name: "T-Shirts MECH Engineer ",
        category: "T-Shirts",
        price: 18.0,
        rating: 4.4,
        image: "/assets/GoodiesMedias/Goodies/tshirts-mec.png",
        images: ["/assets/GoodiesMedias/Goodies/tshirts-mec.png"],
        colors: [{ name: "Navy", hex: "#0a2342" }],
        sizes: ["S", "M", "L", "XL"],
        description: "Official Mechanical Engineering T-Shirt. Built for the future.",
    },
    {
        name: 'T-Shirts "Once/Always a DAUST innovator" ',
        category: "T-Shirts",
        price: 18.0,
        rating: 4.5,
        image: "/assets/GoodiesMedias/Goodies/tshirts-oncealways.png",
        images: ["/assets/GoodiesMedias/Goodies/tshirts-oncealways.png"],
        colors: [{ name: "Various", hex: "#cccccc" }],
        sizes: ["S", "M", "L", "XL"],
        description: "Our signature 'Once/Always' design in a comfortable T-Shirt format.",
    },
    {
        name: 'T-Shirts "Proud Parent" ',
        category: "T-Shirts",
        price: 18.0,
        rating: 4.6,
        image: "/assets/GoodiesMedias/Goodies/tshirts-proud.png",
        images: ["/assets/GoodiesMedias/Goodies/tshirts-proud.png"],
        colors: [{ name: "Various", hex: "#cccccc" }],
        sizes: ["S", "M", "L", "XL"],
        description: "Show your family pride with these comfortable T-Shirts for parents.",
    },
    {
        name: 'T-Shirts "Where Ideas Come to Life" ',
        category: "T-Shirts",
        price: 18.0,
        rating: 4.5,
        image: "/assets/GoodiesMedias/Goodies/tshirts-whereIdeas.png",
        images: ["/assets/GoodiesMedias/Goodies/tshirts-whereIdeas.png"],
        colors: [{ name: "White", hex: "#ffffff" }],
        sizes: ["S", "M", "L", "XL"],
        description: "The motto of DAUST on a premium cotton T-Shirt.",
    },
];
