import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
    products: defineTable({
        name: v.string(),
        category: v.string(),
        price: v.number(),
        rating: v.number(),
        badge: v.optional(v.string()),
        image: v.string(),
        images: v.optional(v.array(v.string())),
        colors: v.optional(v.array(v.object({
            name: v.string(),
            hex: v.string(),
        }))),
        sizes: v.optional(v.array(v.string())),
        logos: v.optional(v.array(v.object({
            id: v.string(),
            name: v.string(),
            image: v.optional(v.string()),
            description: v.optional(v.string()),
            positions: v.optional(v.array(v.string())),
        }))),
        logoImages: v.optional(v.any()),
        description: v.optional(v.string()),
        collection: v.optional(v.string()),
        stock: v.optional(v.number()),
        type: v.optional(v.string()),
        shippingTimeline: v.optional(v.string()),
        hoodieTypes: v.optional(v.array(v.string())),
    }),
    productSets: defineTable({
        name: v.string(),
        description: v.optional(v.string()),
        products: v.array(v.object({
            productId: v.id("products"),
            quantity: v.number(),
            selectedColor: v.optional(v.union(v.string(), v.null())),
            selectedSize: v.optional(v.union(v.string(), v.null())),
            selectedLogo: v.optional(v.union(v.string(), v.null())),
        })),
        specialPrice: v.number(),
        image: v.optional(v.string()),
        badge: v.optional(v.string()),
        isActive: v.optional(v.boolean()),
    }),
    collections: defineTable({
        name: v.string(),
        slug: v.string(),
        description: v.optional(v.string()),
        image: v.optional(v.string()),
    }).index("by_slug", ["slug"]),
    categories: defineTable({
        name: v.string(),
    }),
    orders: defineTable({
        orderId: v.string(),
        naboopayOrderId: v.optional(v.string()),
        customer: v.object({
            name: v.string(),
            phone: v.string(),
            location: v.string(),
        }),
        items: v.array(v.object({
            name: v.string(),
            qty: v.number(),
            price: v.number(),
            hoodieType: v.optional(v.string()),
            color: v.optional(v.string()),
            size: v.optional(v.string()),
            logo: v.optional(v.string()),
            logoPosition: v.optional(v.string()),
            frontLogo: v.optional(v.string()),
            backLogo: v.optional(v.string()),
            sideLogo: v.optional(v.string()),
            isProductSet: v.optional(v.boolean()),
            productSetName: v.optional(v.string()),
        })),
        subtotal: v.number(),
        deliveryFee: v.number(),
        total: v.number(),
        status: v.string(),
        paymentMethod: v.optional(v.string()),
        paymentStorageId: v.optional(v.id("_storage")),
        proofOfPaymentUrl: v.optional(v.string()),
        naboopayCheckoutUrl: v.optional(v.string()),
        createdAt: v.number(),
    }),
});
