import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
    users: defineTable({
        name: v.string(),
        email: v.string(),
        passwordHash: v.string(),
        referral_code: v.string(),
        referral_count: v.number(),
        coupon_percent: v.number(),
        coupon_used: v.boolean(),
        loginAttempts: v.optional(v.number()),
        lockedUntil: v.optional(v.number()),
        resetToken: v.optional(v.string()),
        resetTokenExpiry: v.optional(v.number()),
    })
        .index("by_email", ["email"])
        .index("by_referral_code", ["referral_code"])
        .index("by_reset_token", ["resetToken"]),

    products: defineTable({
        name: v.string(),
        category: v.string(),
        price: v.number(),
        rating: v.number(),
        badge: v.optional(v.string()),
        image: v.string(),
        images: v.optional(v.array(v.string())),
        colors: v.optional(v.array(v.object({
            name: v.string(),
            hex: v.string(),
        }))),
        sizes: v.optional(v.array(v.string())),
        logos: v.optional(v.array(v.object({
            id: v.string(),
            name: v.string(),
            image: v.optional(v.string()),
            description: v.optional(v.string()),
            positions: v.optional(v.array(v.string())),
        }))),
        logoImages: v.optional(v.any()),
        logoCombinations: v.optional(v.array(v.object({
            logoIds: v.array(v.string()),
            image: v.string(),
        }))),
        description: v.optional(v.string()),
        collection: v.optional(v.string()),
        stock: v.optional(v.number()),
        type: v.optional(v.string()),
        shippingTimeline: v.optional(v.string()),
        hoodieTypes: v.optional(v.array(v.string())),
        hasCropTopOption: v.optional(v.boolean()),
        buyingPrice: v.optional(v.number()),
    }),
    productSets: defineTable({
        name: v.string(),
        description: v.optional(v.string()),
        products: v.array(v.object({
            productId: v.id("products"),
            quantity: v.number(),
            selectedColor: v.optional(v.union(v.string(), v.null())),
            selectedSize: v.optional(v.union(v.string(), v.null())),
            selectedLogo: v.optional(v.union(v.string(), v.null())),
        })),
        specialPrice: v.number(),
        image: v.optional(v.string()),
        badge: v.optional(v.string()),
        isActive: v.optional(v.boolean()),
    }),
    collections: defineTable({
        name: v.string(),
        slug: v.string(),
        description: v.optional(v.string()),
        image: v.optional(v.string()),
    }).index("by_slug", ["slug"]),
    categories: defineTable({
        name: v.string(),
    }),
    orders: defineTable({
        orderId: v.string(),
        naboopayOrderId: v.optional(v.string()),
        customer: v.object({
            name: v.string(),
            phone: v.string(),
            location: v.string(),
        }),
        items: v.array(v.object({
            productId: v.optional(v.string()),
            name: v.string(),
            qty: v.number(),
            price: v.number(),
            hoodieType: v.optional(v.string()),
            isCropTop: v.optional(v.boolean()),
            color: v.optional(v.string()),
            size: v.optional(v.string()),
            frontLogo: v.optional(v.string()),
            backLogo: v.optional(v.string()),
            sideLogo: v.optional(v.string()),
            isProductSet: v.optional(v.boolean()),
            productSetName: v.optional(v.string()),
        })),
        subtotal: v.number(),
        deliveryFee: v.number(),
        discount: v.optional(v.number()),
        total: v.number(),
        status: v.string(),
        statusHistory: v.optional(v.array(v.object({
            status: v.string(),
            timestamp: v.number(),
        }))),
        paymentMethod: v.optional(v.string()),
        paymentStorageId: v.optional(v.id("_storage")),
        proofOfPaymentUrl: v.optional(v.string()),
        naboopayCheckoutUrl: v.optional(v.string()),
        createdAt: v.number(),
        buyerUserId: v.optional(v.string()),
        referralCode: v.optional(v.string()),
        referralDiscount: v.optional(v.number()),
        couponDiscount: v.optional(v.number()),
        couponApplied: v.optional(v.boolean()),
        referralTracked: v.optional(v.boolean()),
    }),
    adminSessions: defineTable({
        token: v.string(),
        expiresAt: v.number(),
        createdAt: v.number(),
        role: v.optional(v.union(v.literal("manager"), v.literal("partner"))),
    }).index("by_token", ["token"]),
    siteSettings: defineTable({
        heroMedia: v.optional(v.array(v.object({
            storageId: v.string(),
            type: v.union(v.literal("image"), v.literal("video")),
        }))),
        reelVideos: v.optional(v.array(v.string())),
    }),
});
